# -*- coding: utf-8 -*-
"""code_student_barcode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0bzp3GZXSuv2NymluKowSvHIuiAcub7
"""

!pip install python-barcode pillow openpyxl pandas



import pandas as pd
import os
from barcode import Code128
from barcode.writer import ImageWriter
from openpyxl import load_workbook
from openpyxl.drawing.image import Image as XLImage
from openpyxl.utils import get_column_letter
from google.colab import files

# ---------- STEP 1: UPLOAD INPUT EXCEL FILES ----------
print("📂 Please upload the two Excel files:")
uploaded = files.upload()

sheet1_path = [f for f in uploaded.keys() if 'sheet1' in f.lower()][0]
sheet2_path = [f for f in uploaded.keys() if 'sheet2' in f.lower()][0]

sheet1 = pd.read_excel(sheet1_path)
sheet2 = pd.read_excel(sheet2_path)
print("\n✅ Sheet 1 and Sheet 2 Loaded Successfully!")

# ---------- STEP 2: MERGE BOTH SHEETS ----------
merged = pd.merge(sheet1, sheet2, on=['Barcode', 'Bundle_No'], how='inner')
final_df = merged[['Serial_No_1', 'Roll_No', 'Name', 'Subject_Name',
                   'Barcode', 'Bundle_No', 'Marks', 'Serial_No_2']]

# ---------- STEP 3: CREATE BARCODE FOLDER ----------
barcode_folder = "/content/barcodes"
os.makedirs(barcode_folder, exist_ok=True)

# ---------- STEP 4: GENERATE BARCODES (no text shown) ----------
barcode_images = []
for _, row in final_df.iterrows():
    code = str(row['Barcode']).zfill(6)
    img_path = os.path.join(barcode_folder, f"{code}.png")

    try:
        barcode_obj = Code128(code, writer=ImageWriter())
        with open(img_path, "wb") as f:
            barcode_obj.write(f, options={
                'write_text': False,      # 🔥 hide 6-digit text
                'module_width': 0.4,
                'module_height': 25,
                'quiet_zone': 2
            })
        barcode_images.append(img_path)
    except Exception as e:
        print(f"⚠️ Failed to generate barcode {code}: {e}")

print(f"\n✅ Generated {len(barcode_images)} barcode images in {barcode_folder}")

# ---------- STEP 5: SAVE MERGED DATA ----------
output_path = "/content/merged_with_barcodes.xlsx"
final_df.to_excel(output_path, index=False)

# ---------- STEP 6: INSERT BARCODE IMAGES ----------
wb = load_workbook(output_path)
ws = wb.active
barcode_col_idx = ws.max_column + 1
barcode_col_letter = get_column_letter(barcode_col_idx)
ws.cell(row=1, column=barcode_col_idx, value="Barcode_Image")

for idx, img_path in enumerate(barcode_images, start=2):
    if os.path.exists(img_path):
        img = XLImage(img_path)
        img.width = 180
        img.height = 70
        ws.add_image(img, f"{barcode_col_letter}{idx}")
        ws.row_dimensions[idx].height = 60
    else:
        print(f"⚠️ Missing image file: {img_path}")

ws.column_dimensions[barcode_col_letter].width = 30
wb.save(output_path)

# ---------- STEP 7: DOWNLOAD ----------
print("\n🎯 Final Excel with Barcode Images created successfully!")
files.download(output_path)